/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.psm;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    String palabra;
    Jugadores j1;
    Jugadores j2;
    boolean jugar = true;
    char[] letras;
    int intentos = 5;
    ImageIcon icono = new ImageIcon("src/imagenes/ahorcado.png");

    public Frame() {
        this.setTitle("El ahorcado");
        
        j1 = new Jugadores();
        j2 = new Jugadores();
        initComponents();
        bJugar1.setVisible(false);
        lpuntuajej1.setText(String.valueOf(j1.getPuntos()));
        lpuntuajej2.setText(String.valueOf(j2.getPuntos()));
        if (jugar == true) {
            lj1.setForeground(Color.red);
        } else {
            lj2.setForeground(Color.red);
        }
        dibujo.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bJugar = new javax.swing.JButton();
        lPalabra = new javax.swing.JLabel();
        bJugar1 = new javax.swing.JButton();
        lGanar = new javax.swing.JLabel();
        lj2 = new javax.swing.JLabel();
        lj1 = new javax.swing.JLabel();
        bReset = new javax.swing.JButton();
        lPuntosj1 = new javax.swing.JLabel();
        lpuntuajej1 = new javax.swing.JLabel();
        lPuntosj2 = new javax.swing.JLabel();
        lpuntuajej2 = new javax.swing.JLabel();
        Resetear = new javax.swing.JButton();
        dibujo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Escribir una palabra...");
        jTextField1.setMaximumSize(new java.awt.Dimension(91, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(91, 20));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));

        bJugar.setText("Jugar");
        bJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugarActionPerformed(evt);
            }
        });
        getContentPane().add(bJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        lPalabra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lPalabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPalabra.setMaximumSize(new java.awt.Dimension(100, 22));
        lPalabra.setMinimumSize(new java.awt.Dimension(100, 22));
        lPalabra.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(lPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 250, 50));

        bJugar1.setText("Probar");
        bJugar1.setMaximumSize(new java.awt.Dimension(59, 23));
        bJugar1.setMinimumSize(new java.awt.Dimension(59, 23));
        bJugar1.setPreferredSize(new java.awt.Dimension(59, 23));
        bJugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bJugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, 30));

        lGanar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lGanar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGanar.setMaximumSize(new java.awt.Dimension(100, 22));
        lGanar.setMinimumSize(new java.awt.Dimension(100, 22));
        lGanar.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(lGanar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 270, 30));

        lj2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lj2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lj2.setText("J2");
        lj2.setMaximumSize(new java.awt.Dimension(40, 40));
        lj2.setMinimumSize(new java.awt.Dimension(40, 40));
        lj2.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(lj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        lj1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lj1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lj1.setText("J1");
        lj1.setMaximumSize(new java.awt.Dimension(40, 40));
        lj1.setMinimumSize(new java.awt.Dimension(40, 40));
        lj1.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(lj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        bReset.setText("Cambiar jugardor");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        lPuntosj1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lPuntosj1.setText("Puntos:");
        getContentPane().add(lPuntosj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lpuntuajej1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lpuntuajej1.setText("0");
        getContentPane().add(lpuntuajej1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, -1));

        lPuntosj2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lPuntosj2.setText("Puntos:");
        getContentPane().add(lPuntosj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        lpuntuajej2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lpuntuajej2.setText("0");
        getContentPane().add(lpuntuajej2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 80, -1));

        Resetear.setText("Reset");
        Resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetearActionPerformed(evt);
            }
        });
        getContentPane().add(Resetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 80, -1));

        dibujo.setMaximumSize(new java.awt.Dimension(101, 112));
        dibujo.setPreferredSize(new java.awt.Dimension(101, 112));
        getContentPane().add(dibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void bJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugarActionPerformed

        palabra = jTextField1.getText();
        letras = new char[palabra.length()];
        for (int i = 0; i < palabra.length(); i++) {
            letras[i] = palabra.charAt(i);
            lPalabra.setText(lPalabra.getText() + "- ");
        }
        if (jugar == true) {
            jTextField1.setText("Escribe una letra J2");
        } else {
            jTextField1.setText("Escribe una letra J1");
        }

        bJugar.setVisible(false);
        bJugar1.setVisible(true);
    }//GEN-LAST:event_bJugarActionPerformed

    private void bJugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugar1ActionPerformed
        String intento = jTextField1.getText();
        String aux;
        boolean encontrado=false;
        for (int i = 0; i < palabra.length(); i++) {

            if (letras[i] == intento.charAt(0)) {
                aux = lPalabra.getText();
                aux = aux.substring(0, i * 2) + letras[i] + aux.substring(i * 2 + 1, aux.length());

                lPalabra.setText(aux);
                encontrado=true;
            } 

        }
        if (encontrado!=true){
            if (intentos != 0) {
                    intentos--;
                }
                switch (intentos) {

                    case 4:
                        icono = new ImageIcon("src/imagenes/ahorcado1.png");
                        dibujo.setIcon(icono);
                        break;
                    case 3:
                        icono = new ImageIcon("src/imagenes/ahorcado2.png");
                        dibujo.setIcon(icono);
                        break;
                    case 2:
                        icono = new ImageIcon("src/imagenes/ahorcado3.png");
                        dibujo.setIcon(icono);
                        break;
                    case 1:
                        icono = new ImageIcon("src/imagenes/ahorcado4.png");
                        dibujo.setIcon(icono);
                        break;
                    case 0:
                        icono = new ImageIcon("src/imagenes/ahorcado5.png");
                        dibujo.setIcon(icono);
                        if (jugar == true) {
                            j2.setPuntos(-50);
                            lGanar.setText("Has Perdido J2");
                            lpuntuajej2.setText(String.valueOf(j2.getPuntos()));
                        } else {
                            lGanar.setText("Has Perdido J1");
                            j1.setPuntos(-50);
                            lpuntuajej1.setText(String.valueOf(j1.getPuntos()));
                        }
                        break;
                    default:
                        break;
                }
        }else{
            encontrado=false;
        }
        for (int i = 0; i < lPalabra.getText().length(); i++) {
            if (!lPalabra.getText().contains("-")) {

                if (jugar == true) {
                    j2.setPuntos(100);
                    lGanar.setText("Has Ganado J2");
                    lpuntuajej2.setText(String.valueOf(j2.getPuntos()));
                } else {
                    lGanar.setText("Has Ganado J1");
                    j1.setPuntos(100);
                    lpuntuajej1.setText(String.valueOf(j1.getPuntos()));
                }
            }
        }
    }//GEN-LAST:event_bJugar1ActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        jTextField1.setText("Escribir una palabra...");
        lPalabra.setText("");
        lGanar.setText("");
        bJugar.setVisible(true);
        bJugar1.setVisible(false);
        ImageIcon icono = new ImageIcon("src/imagenes/ahorcado.png");
        dibujo.setIcon(icono);
        intentos=5;
        if (jugar == true) {
            jugar = false;
        } else {
            jugar = true;
        }
        if (jugar == true) {
            lj1.setForeground(Color.red);
            lj2.setForeground(Color.black);
        } else {
            lj2.setForeground(Color.red);
            lj1.setForeground(Color.black);
        }
    }//GEN-LAST:event_bResetActionPerformed

    private void ResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetearActionPerformed
        ImageIcon icono = new ImageIcon("src/imagenes/ahorcado.png");
        dibujo.setIcon(icono);
        intentos=5;
        jTextField1.setText("Escribir una palabra...");
        lPalabra.setText("");
        lGanar.setText("");
        bJugar.setVisible(true);
        bJugar1.setVisible(false);
        j2.setPuntos(0);
        lpuntuajej2.setText(String.valueOf(j2.getPuntos()));
        j1.setPuntos(0);
        lpuntuajej1.setText(String.valueOf(j1.getPuntos()));
    }//GEN-LAST:event_ResetearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Resetear;
    private javax.swing.JButton bJugar;
    private javax.swing.JButton bJugar1;
    private javax.swing.JButton bReset;
    private javax.swing.JLabel dibujo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lGanar;
    private javax.swing.JLabel lPalabra;
    private javax.swing.JLabel lPuntosj1;
    private javax.swing.JLabel lPuntosj2;
    private javax.swing.JLabel lj1;
    private javax.swing.JLabel lj2;
    private javax.swing.JLabel lpuntuajej1;
    private javax.swing.JLabel lpuntuajej2;
    // End of variables declaration//GEN-END:variables
}
